version: '3.7'

services: 
  postgres:
    image: 'postgres:11'
    container_name: postgres
    ports: 
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 9090:80
          
volumes: 
  springboot-task-tracker-postgres-api-db-volume:
  springboot-task-tracker-postgres-api-pgadmin-volume:

networks:
  default:
    name: springboot-task-tracker-postgres-api-network